site_name: Python Notes (Lekhraj Dinkar)
site_description: Documentation for ETL processes using PySpark
site_author: Lekhraj Dinkar

# Navigation based on your Notes folder
nav:
  - PySpark:
      - index: 01_pyspark/00_index.md
      - 00_panda: 01_pyspark/00_panda.md
      - 01_setup_locally: 01_pyspark/01_setup_locally.md
      - 02_architecture: 01_pyspark/02_architecture.md
      - 03_ETL_1: 01_pyspark/03_ETL_1.md
      - 03_ETL_2: 01_pyspark/03_ETL_2.md
      - 04_file_format: 01_pyspark/04_file_format.md
      - 100_pyspark_01_start: 01_pyspark/100_pyspark_01_start.md
      - 100_pyspark_02: 01_pyspark/100_pyspark_02.md

  - python fundamental:
      - kickoff: 02_funda/01_kickoff.md
      - index: 02_funda/00_index.md
      - global-function: 02_funda/02_global-function.md

  - Career:
      - Interview : interview.md

extra_css:
  - mkdocs.css

theme:
  font:
    text: Roboto
    code: Roboto Mono
  name: material
  features:
    - navigation.tabs
    - navigation.sections
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      accent: indigo
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: yellow
      accent: indigo

repo_url: https://github.com/lekhrajdinkar/02-etl-pyspark
repo_name: GitHub
edit_uri: edit/main/Notes/

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde

plugins:
  - search
  - markdownextradata
  #- copyfiles

#copyfiles:
  #- deployment/manifest

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/lekhrajdinkar
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/lekhraj-dinkar-25872140/