site_name: Python Notes (Lekhraj Dinkar)
site_description: Documentation for ETL processes using PySpark
site_author: Lekhraj Dinkar
docs_dir: docs

# Navigation based on your Notes folder
nav:
  - PySpark:
      - index: 01_pyspark/index.md
      - 00_panda: 01_pyspark/00_panda.md
      - 01_setup_locally: 01_pyspark/01_setup_locally.md
      - 02_architecture: 01_pyspark/02_architecture.md
      - 03_ETL_1: 01_pyspark/03_ETL_1.md
      - 03_ETL_2: 01_pyspark/03_ETL_2.md
      - 04_file_format: 01_pyspark/04_file_format.md
      - 100_pyspark_01_start: 01_pyspark/100_pyspark_01_start.md
      - 100_pyspark_02: 01_pyspark/100_pyspark_02.md

  - python fundamental:
      - 01_kickoff: 02_funda/01_kickoff.md
      - 00_index: 02_funda/00_index.md
      - 02_global-function: 02_funda/02_global-function.md
      - 03_module+DP: 02_funda/03_module+DP.md
      - 04_programing-style: 02_funda/04_programing-style.md

  - More:
      - chats : chats.md

theme:
  font:
    text: Roboto
    code: Roboto Mono
  name: material
  features:
    - navigation.tabs
    - navigation.sections
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: deep orange
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
  custom_dir: .
extra_css:
  - mkdocs.css

repo_url: https://github.com/lekhrajdinkar/02-etl-pyspark
repo_name: GitHub
edit_uri: edit/main/Notes/

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/lekhrajdinkar
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/lekhraj-dinkar-25872140/